name: Update City Temps

on:
  schedule:
    - cron: "0 18 * * *"      # daily at 18:00 UTC
  workflow_dispatch:          # allow manual runs
  push:
    paths:
      - "scripts/fetch_cities_temp.py"
      - ".github/workflows/fetch_temps.yml"

permissions:
  contents: write             # <-- needed to push with GITHUB_TOKEN

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # If your script needs an API key, expose it like this:
      #   env:
      #     WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      - name: Run script
        run: |
          set -euo pipefail
          python scripts/fetch_cities_temp.py
          test -f assets/data/city_temps.json
          echo "File size:"
          wc -c assets/data/city_temps.json
          echo "First 200 chars:"
          head -c 200 assets/data/city_temps.json || true

      - name: Upload JSON artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: city_temps.json
          path: assets/data/city_temps.json
          if-no-files-found: warn

      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git status

      - name: Commit and push if changed
        run: |
          set -e
          git add assets/data/city_temps.json
          date -u +"%a %b %d %H:%M:%S UTC %Y" > last_update.txt
          git add last_update.txt
          git commit -m "Update city temperatures $(date -u)" || exit 0
          # Protect against non-fast-forward if something else pushed
          git pull --rebase
          git push
